apiVersion: v1
kind: Namespace
metadata:
  name: sppline
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-sample-flask
  namespace: sppline
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: reg-anthos-test.kartaca.com:5000/sppline:$BUILD_NUMBER
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sppline-service
  namespace: sppline
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 10.34.11.228

