apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-sample-flask
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: registry.kartaca.com:5000/sppline:$BUILD_NUMBER
        ports:
        - containerPort: 80
